### ISSUE TITLE
Script broken?

### ISSUE THREAD

**Issue by tr37ion** [jdupl/youtube-dl-channel#1]
I seems your script is broken with newest YT API. Could you fix this, please?

**Comment by jdupl** [comment]
I will check this out

**Comment by jdupl** [comment]
@tr37ion fixed this script. I still have to update my youtube-dl-playlist script.

**Comment by tr37ion** [comment]
That's nice, I will try it later. Thanks.

**Comment by jdupl** [comment]
There I updated the script to work with the new API and only depend on youtube-dl.

**Comment by tr37ion** [comment]
Thank you. It's working great :)
